package tester;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;

import nlp.objects.Sentence;
import nlp.objects.Sentences;
import trie.LeafNode;
import trie.Trie;

public class Paragraph {
	
	private Sentences Paragraph;
	
	/**
	 * Reads a paragraph from the inputFile provided and loads it. POSTags the setences.
	 * @param inputFile
	 */
	public Paragraph(File inputFile) {
		this.Paragraph = new Sentences();
		BufferedReader br = null;
		try {
			br = new BufferedReader(new FileReader(inputFile));
			//TODO Reads only one line from the file.
			String paragraph = br.readLine();
			load(paragraph);
			br.close();
		}
		catch (IOException ioe) {
			ioe.printStackTrace();
			System.err.println("Error reading test data file.");
		}
		
	}
	
	/**
	 * Loads the paragraph provided from paragraph into the list of sentences. POSTags the sentences.
	 * @param paragraph
	 */
	public Paragraph(String paragraph) {
		this.Paragraph = new Sentences();
		load(paragraph);
	}
	
	private void load(String paragraphText) {
		ArrayList<Sentence> sentences = new ArrayList<Sentence>();
		for (String sentenceValue : Arrays.asList(paragraphText.split("\\."))) {
			Sentence sent = new Sentence(sentenceValue);
			sentences.add(sent);
		}
		this.Paragraph.setSentence(sentences);
	}
	
	public void acquireDataModel(Trie trie) {
		for (Sentence sentence : this.Paragraph.getSentence()) {
			LeafNode leafInfo = trie.lookup(sentence);
			if (leafInfo == null) {
				System.err.println("Lookup for -" + sentence.getValue() + " did not return any match.");
			}
			else {
				sentence.setDataModel(leafInfo.getDataModel());
			}
				
		}
	}
	/**
	 * Converts the List of sentences into a xml format which can be read by the plugin.
	 * @return XML in string format.
	 */
	public String toErdXml() {
		//FIXME Implement this
		
		return null;
	}
	
	/**
	 * Saves the xml as generated by toErdXml to a path specified by filepath
	 * @param filepath Absolute path of file to store the file. Provide the extension of the file.
	 */
	public void saveAsXml(String filepath) {
		//FIXME Implement this
	}
	
	@Override
	public String toString() {
		return this.Paragraph.toString();
	}
}